const availableLanguage = [
    { "language": "bash", "name": "Bash" },
    { "language": "c", "name": "C" },
    { "language": "csharp", "name": "C#" },
    { "language": "go", "name": "Go" },
    { "language": "java", "name": "Java" },
    { "language": "javascript", "name": "JavaScript" },
    { "language": "kotlin", "name": "Kotlin" },
    { "language": "lua", "name": "Lua" },
    { "language": "node", "name": "Node.js" },
    { "language": "perl", "name": "Perl" },
    { "language": "php", "name": "PHP" },
    { "language": "python", "name": "Python" },
    { "language": "ruby", "name": "Ruby" },
    { "language": "rust", "name": "Rust" },
    { "language": "swift", "name": "Swift" },
    { "language": "typescript", "name": "TypeScript" },
    { "language": "typescript-node", "name": "TypeScript (Node)" },
    { "language": "scala", "name": "Scala" },
    { "language": "haskell", "name": "Haskell" },
    { "language": "fsharp", "name": "F#" },
    { "language": "clojure", "name": "Clojure" },
    { "language": "ocaml", "name": "OCaml" },
    { "language": "dart", "name": "Dart" },
    { "language": "r", "name": "R" },
    { "language": "elixir", "name": "Elixir" },
    { "language": "erlang", "name": "Erlang" },
    { "language": "julia", "name": "Julia" }
  ]
export default availableLanguage